#!/bin/bash

PATH=/var/lib/loadbalancer.org/check/:/usr/local/sbin/:/bin/:/sbin/

#Variables passed by ldirectord.
# $1 = VIP Address
# $2 = VIP Port
# $3 = Real Server IP
# $4 = Real Server Port

VIP=$1

ipvsadm --list | grep $VIP -a1 | grep Route >/dev/null
ec=$?
if [ $ec -eq 1 ]
then
	if [[ $(iptables -L -v | grep -c echo-request) -eq 0 ]]
	then
		iptables -A INPUT -d $VIP -p icmp --icmp-type 8 -j DROP
	fi
elif [ $ec -eq 0 ]
then
	if [[ $(iptables -L -v | grep -c echo-request) -eq 1 ]]
	then  
		iptables -D INPUT -d $VIP -p icmp --icmp-type 8 -j DROP
	fi
fi

# Uncomment the healthcheck you actually want to use

#sh check-ipv6-ping  $1 $2 $3 $4
#sh Exchange-2013.sh $1 $2 $3 $4
#sh http_ntlm_proxy_check.sh $1 $2 $3 $4
#sh Multi-port-check.sh $1 $2 $3 $4
#sh proxy-check.sh $1 $2 $3 $4
#sh SMTP-check.sh $1 $2 $3 $4
#sh sni-check-v2.sh $1 $2 $3 $4
#sh DICOM-C-ECHO $1 $2 $3 $4
#sh Exchange_IMAP.sh $1 $2 $3 $4
#sh icmp-firewall-check $1 $2 $3 $4
sh ping.sh $1 $2 $3 $4
#sh sip_check.pl $1 $2 $3 $4
#sh sni-check.sh $1 $2 $3 $4



