#!/bin/bash -x 

PATH=/var/lib/loadbalancer.org/check/:/usr/bin/:/usr/local/sbin/:/bin/:/sbin/

#Variables passed by ldirectord.
# $1 = VIP Address
# $2 = VIP Port
# $3 = Real Server IP
# $4 = Real Server Port

VIP=$1
VPT=$2
RIP=$3
RPT=$4

if [[ $VIP =~ ^([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$ ]]; then
	ipt=iptables
elif [[ $VIP =~ ^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$ ]]; then
        ipt=ip6tables
else
        firewallmark=/etc/rc.d/auto_fwmarks/fwmark-$VIP
	FWM=$VIP
	if [ -f $firewallmark ]; then 	
		VIP=$(cat $firewallmark | grep D | /usr/bin/head -1 | cut -d' ' -f9)
		RPT=$(cat $firewallmark | grep D | cut -d' ' -f11)
		RPT=$(echo $RPT | tr -d '\n')
	else
		# echo "not autofirewallmark"
		# We do not know how to deal with manual firewall marks yet. 
		# We will exit 1 here to force a healthcheck failure

		exit 1;
		# VIP=$(echo $(cat /etc/rc.d/rc.firewall | grep $(cat /etc/rc.d/rc.firewall  | grep $FWM | grep set-mark | cut -d' ' -f9 | head -1 | tr -d '$') |head -1) | cut -d '=' -f2 | tr -d '"')		
	fi
fi

if [[ $VIP =~ .*:.* ]]
then
	ipt=ip6tables
else
        ipt=iptables
fi

ipvsadm --list | grep $VIP -a1 | grep Route >/dev/null
ec=$?
if [ $ec -eq 1 ]
then
	if [[ $($ipt -L -v | grep $VIP | grep -c echo-request)  -eq 0 ]]
	then
		$ipt -A INPUT -d $VIP -p icmp --icmp-type 8 -j DROP
	fi
elif [ $ec -eq 0 ]
then
	if [[ $($ipt -L -v | grep $VIP | grep -c echo-request) -eq 1 ]]
	then  
		$ipt -D INPUT -d $VIP -p icmp --icmp-type 8 -j DROP
	fi
fi

# Uncomment the healthcheck you actually want to use

#sh check-ipv6-ping $VIP $VPT $RIP $RPT
#sh Exchange-2013.sh $VIP $VPT $RIP $RPT
#sh http_ntlm_proxy_check.sh $VIP $VPT $RIP $RPT
sh Multi-port-check.sh $VIP $VPT $RIP "$RPT"
#sh proxy-check.sh $VIP $VPT $RIP $RPT
#sh SMTP-check.sh $VIP $VPT $RIP $RPT
#sh sni-check-v2.sh $VIP $VPT $RIP $RPT
#sh DICOM-C-ECHO $VIP $VPT $RIP $RPT
#sh Exchange_IMAP.sh $VIP $VPT $RIP $RPT
#sh icmp-firewall-check $VIP $VPT $RIP $RPT
#sh ping.sh $VIP $VPT $RIP $RPT
#sh sip_check.pl $VIP $VPT $RIP $RPT
#sh sni-check.sh $VIP $VPT $RIP $RPT

