#!/bin/bash -x
PATH=/usr/bin:/var/lib/loadbalancer.org/check/:/usr/local/sbin/:/bin/:/sbin/
#
# Layer7 iptables DROP if all real servers are down.
# adapt firewall rules to suit - this just drops icmp type 8 packets
# Created by Andrew Smalley ' loadbalancer.org (c)2017 June 6
VIP=ppmy
VIPIP=$1

RIPS=$(echo "show stat" | socat unix-connect:/var/run/haproxy.stat stdio | grep $VIP | cut -d"," -f2 | grep -v "FRONTEND" | grep -v "backup" | grep -v "BACKEND")
for RIP in $RIPS; do
   if [[ $(echo "show stat" | socat unix-connect:/var/run/haproxy.stat stdio | grep $VIP | grep $RIP | cut -d"," -f18) -eq "UP" ]];
        then
                UP=1;
        fi
done
if [ $UP -eq 1 ]
then
        iptables -L -v | grep $VIPIP | cut -d' ' -f11 | grep DROP >/dev/null
        if [ $? -eq 1 ]
        then
                iptables -A INPUT -d $VIPIP -j DROP   # DROP All Traffic
        fi
elif [ $UP -eq 0 ]
then
        iptables -L -v | grep $VIPIP | cut -d' ' -f11 | grep DROP >/dev/null
        if [ $? -eq 0  ]
        then
                iptables -D INPUT -d $VIPIP -j DROP   # ALLOW All Traffic
        fi
fi

# Uncomment the healthcheck you actually want to use

#sh check-ipv6-ping  $1 $2 $3 $4
#sh Exchange-2013.sh $1 $2 $3 $4
#sh http_ntlm_proxy_check.sh $1 $2 $3 $4
#sh Multi-port-check.sh $1 $2 $3 $4
#sh proxy-check.sh $1 $2 $3 $4
#sh SMTP-check.sh $1 $2 $3 $4
#sh sni-check-v2.sh $1 $2 $3 $4
#sh DICOM-C-ECHO $1 $2 $3 $4
#sh Exchange_IMAP.sh $1 $2 $3 $4
#sh icmp-firewall-check $1 $2 $3 $4
sh ping.sh $1 $2 $3 $4
#sh sip_check.pl $1 $2 $3 $4
#sh sni-check.sh $1 $2 $3 $4

