#!/bin/bash
###############################################################################
# Fijifilm C-MOVE Healthcheck v0.1 
#
# (c)loadbalancer.org 2021 - Created by Andrew Smalley
#
# Healthchck uses /usr/local/bin/movescu 
#
# any of the options can be defined in the check
#
###############################################################################
# virtual service and port or source should not need altering




VIRTUALSERVICE=$1
VIRTUALPORT=$2
VIRTUALSOURCE=$5
CHECK_TIMEOUT=5

# this does not work with auto firewall marks, it can be made to do so simply. 
# this does not work with manual firewall marks, that would be interesting to 
# create but can also be done with less ease (I tried before)
#
# Be aware DICOM will very likely respond on a different port  
# Timeout is suggested to be 30 seconds -ta   --acse-timeout       [s]econds: integer (default: 30)
SCU_TIMEOUT=30

# [a]etitle: string
#                               set my calling AE title (default: FINDSCU)
AET="MOVESCU"

# [a]etitle: string
#                               set called AE title of peer (default: ANY-SCP)
ACT="ANY-SCP"

# [a]etitle: string
                                set move destinat. AE title (default: MOVESCU)
AEM="MOVESCU"                                 

# DICOM PEER and PORT
PEER=$3
PORT=$4


#network options: customise and add these to options
#
#  override matching keys:
#    -k    --key                [k]ey: gggg,eeee="str", path or dict. name="str"
#                               override matching key

KEY="" #"-k "
#  query information model:
#    -W    --worklist           use modality worklist information model (default)
WORKLIST="" #"-W "
#    -P    --patient            use patient root information model
PATITENT="" #"-P "
#    -S    --study              use study root information model
STUDY="" #"-S "
#    -O    --psonly             use patient/study only information model
PSONLY="" #"-O "

# options: 
#                               set my calling options
OPTIONS=" -aet $AET -act $ACT -aem $AEM $KEY $WORKLIST $PATITENT $STUDY $PSONLY --ignore-peer-cert --null-passwd "

# dcmfile_in: dcmfile-in  DICOM file or directory to be transmitted
DCMFILEIN=""



# Below likely does not need editing
#
# Use VirtualService Port if Real Server port is inherited. 
if [ ! $PORT ]; then
  PORT=$2
fi

MODE="--quiet " # --debug

# The healthcheck



timeout $CHECK_TIMEOUT $HEALTH_CHECK_CMD $MODE -to $SCU_TIMEOUT \
    $OPTIONS $PEER $PORT $DCMFILEIN

exit $?



exit 99





exit 99




$dcmtk: movescu v3.6.0 2011-01-06 $

movescu: DICOM retrieve (C-MOVE) SCU
usage: movescu [options] peer port [dcmfile-in...]

parameters:
  peer                           hostname of DICOM peer
  port                           tcp/ip port number of peer
  dcmfile-in                     DICOM query file(s)

general options:
  -h      --help                 print this help text and exit
          --version              print version information and exit
          --arguments            print expanded command line arguments
  -q      --quiet                quiet mode, print no warnings and errors
  -v      --verbose              verbose mode, print processing details
  -d      --debug                debug mode, print debug information
  -ll     --log-level            [l]evel: string constant
                                 (fatal, error, warn, info, debug, trace)
                                 use level l for the logger
  -lc     --log-config           [f]ilename: string
                                 use config file f for the logger
network options:
  override matching keys:
    -k    --key                  [k]ey: gggg,eeee="str" or dict. name="str"
                                 override matching key
  query information model:
    -P    --patient              use patient root information model (default)
    -S    --study                use study root information model
    -O    --psonly               use patient/study only information model
  application entity titles:
    -aet  --aetitle              [a]etitle: string
                                 set my calling AE title (default: MOVESCU)
    -aec  --call                 [a]etitle: string
                                 set called AE title of peer (default: ANY-SCP)
    -aem  --move                 [a]etitle: string
                                 set move destinat. AE title (default: MOVESCU)
  preferred network transfer syntaxes (incoming associations):
    +x=   --prefer-uncompr       prefer explicit VR local byte order (default)
    +xe   --prefer-little        prefer explicit VR little endian TS
    +xb   --prefer-big           prefer explicit VR big endian TS
    +xs   --prefer-lossless      prefer default JPEG lossless TS
    +xy   --prefer-jpeg8         prefer default JPEG lossy TS for 8 bit data
    +xx   --prefer-jpeg12        prefer default JPEG lossy TS for 12 bit data
    +xv   --prefer-j2k-lossless  prefer JPEG 2000 lossless TS
    +xw   --prefer-j2k-lossy     prefer JPEG 2000 lossy TS
    +xt   --prefer-jls-lossless  prefer JPEG-LS lossless TS
    +xu   --prefer-jls-lossy     prefer JPEG-LS lossy TS
    +xm   --prefer-mpeg2         prefer MPEG2 Main Profile @ Main Level TS
    +xh   --prefer-mpeg2-high    prefer MPEG2 Main Profile @ High Level TS
    +xr   --prefer-rle           prefer RLE lossless TS
    +xd   --prefer-deflated      prefer deflated expl. VR little endian TS
    +xi   --implicit             accept implicit VR little endian TS only
    +xa   --accept-all           accept all supported transfer syntaxes
  proposed transmission transfer syntaxes (outgoing associations):
    -x=   --propose-uncompr      propose all uncompressed TS, explicit VR
                                 with local byte ordering first (default)
    -xe   --propose-little       propose all uncompressed TS, explicit VR
                                 little endian first
    -xb   --propose-big          propose all uncompressed TS, explicit VR
                                 big endian first
    -xi   --propose-implicit     propose implicit VR little endian TS only
  port for incoming network associations:
          --no-port              no port for incoming associations (default)
    +P    --port                 [n]umber: integer
                                 port number for incoming associations
  handling of illegal datasets following 'pending' move responses:
    -pi   --pending-ignore       assume no dataset present (default)
    -pr   --pending-read         read and ignore dataset
  other network options:
    -to   --timeout              [s]econds: integer (default: unlimited)
                                 timeout for connection requests
    -ta   --acse-timeout         [s]econds: integer (default: 30)
                                 timeout for ACSE messages
    -td   --dimse-timeout        [s]econds: integer (default: unlimited)
                                 timeout for DIMSE messages
    -pdu  --max-pdu              [n]umber of bytes: integer (4096..131072)
                                 set max receive pdu to n bytes (default: 16384)
    -dhl  --disable-host-lookup  disable hostname lookup
          --repeat               [n]umber: integer
                                 repeat n times
          --abort                abort association instead of releasing it
          --ignore               ignore store data, receive but do not store
          --cancel               [n]umber: integer
                                 cancel after n responses (default: never)
    -up   --uid-padding          silently correct space-padded UIDs
output options:
  general:
    -od   --output-directory     [d]irectory: string (default: ".")
                                 write received objects to existing directory d
  bit preserving mode:
    -B    --normal               allow implicit format conversions (default)
    +B    --bit-preserving       write data exactly as read
  output file format:
    +F    --write-file           write file format (default)
    -F    --write-dataset        write data set without file meta information
  output transfer syntax (not with --bit-preserving or compressed transmission):
    +t=   --write-xfer-same      write with same TS as input (default)
    +te   --write-xfer-little    write with explicit VR little endian TS
    +tb   --write-xfer-big       write with explicit VR big endian TS
    +ti   --write-xfer-implicit  write with implicit VR little endian TS
    +td   --write-xfer-deflated  write with deflated expl. VR little endian TS
  post-1993 value representations (not with --bit-preserving):
    +u    --enable-new-vr        enable support for new VRs (UN/UT) (default)
    -u    --disable-new-vr       disable support for new VRs, convert to OB
  group length encoding (not with --bit-preserving):
    +g=   --group-length-recalc  recalculate group lengths if present (default)
    +g    --group-length-create  always write with group length elements
    -g    --group-length-remove  always write without group length elements
  length encoding in sequences and items (not with --bit-preserving):
    +e    --length-explicit      write with explicit lengths (default)
    -e    --length-undefined     write with undefined lengths
  data set trailing padding (not with --write-dataset or --bit-preserving):
    -p    --padding-off          no padding (default)
    +p    --padding-create       [f]ile-pad [i]tem-pad: integer
                                 align file on multiple of f bytes
                                 and items on multiple of i bytes
  deflate compression level (only with --write-xfer-deflated/same):
    +cl   --compression-level    [l]evel: integer (default: 6)
                                 0=uncompressed, 1=fastest, 9=best compression
